config/routes.rb
Rails.application.routes.draw do

  get '/images_display' => 'images_display#display'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_display_controller.rb
class ImagesDisplayController < ApplicationController
  def display
    @hash = params[:q].split(" ").join
    url = "https://api.social-searcher.com/v2/search?q=#{@hash}&network=instagram&key=97035760e6ee719b7fd7545a87d9e9d1"
    @response = HTTParty.get(url)
    @array = @response["posts"]
    @render = []
    @array.each do |array_element|
    @render << array_element["image"]
    end

    url = "https://api.social-searcher.com/v2/search?q=#{@hash}&network=tumblr&key=97035760e6ee719b7fd7545a87d9e9d1"
    @response3 = HTTParty.get(url)
    @array = @response3["posts"]
    @render3 = []
    @array.each do |array_element|
    @render3 << array_element["image"]
    end

    url = "https://api.social-searcher.com/v2/search?q=#{@hash}&network=youtube&key=97035760e6ee719b7fd7545a87d9e9d1"
    @response2 = HTTParty.get(url)
    @array2 = @response2["posts"]
    @render2 = []
    @array2.each do |array_element|
    video = array_element["url"].split("=")
    video = video[1]
    @render2 << video
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_display_helper.rb
module ImagesDisplayHelper
end

app/views/home/index.html.erb
<body class="body">

<%=image_tag"logo.png", class:"logo"%>

<span class="form1"> <%= form_tag(images_display_path, method: "get") do %>
 <%= label_tag(:q, "Just VIMAGE it") %>
 <font color="black" class="search_bar"><%= text_field_tag(:q) %></font>
 <font color="black"><%= submit_tag("GO") %></font>
<% end %>
</span>

<h5 class="title1">videos & images on one page </h5>




</body>

app/views/images_display/display.html.erb
<body class="display_body">

<div class="logo23"><%=image_tag("logo4.png", options={})%></div>

<div class="form"> <%= form_tag(images_display_path, method: "get") do %>
  <%= label_tag(:q, "Just VIMAGE it") %>
  <font color="black" class="search_bar"><%= text_field_tag(:q) %></font>
  <font color="black"><%= submit_tag("GO") %></font>
  <% end %>
</div>

<h5 class="title">videos & images on one page </h5>

<hr></hr>

<div class="video">
<% @render2.each do |video| %>
  <iframe class:"video_style" width="560" height="315" src="https://www.youtube.com/embed/<%=video%>" frameborder="0" allowfullscreen></iframe>
<% end %>
</div>

<div class="images">
<% @render.each do |image| %>
  <img class="img-responsive" alt="Responsive image" src="<%=image%>" />
<% end %>
</div>



<div class="images">
<% @render3.each do |image| %>
  <img class="img-responsive" alt="Responsive image" src="<%=image%>" />
<% end %>
</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>